// Turns the balance and perk-stress JSON into one markdown report, diffed
// against a committed baseline.
//
// Balance is worked on as its own pass, not during feature work — so the
// harnesses no longer fail anything (see packages/sim/scripts/balance.ts). What
// replaces the gate is this: a report that says what MOVED. A feature commit
// that quietly costs a build 20 points shows up here as a changed file in
// review, without ever turning a build red.
//
// Usage:
//   node scripts/balance-report.mjs                  # regenerate from artifacts/
//   node scripts/balance-report.mjs --rebaseline     # adopt current as the new reference
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const P = {
  balance: `${ROOT}/artifacts/balance.json`,
  diversity: `${ROOT}/artifacts/diversity.json`,
  baseline: `${ROOT}/artifacts/balance-baseline.json`,
  out: `${ROOT}/artifacts/balance-report.md`,
};
const SWING = 5; // points; below this is seed noise, not a change worth reading

const read = (p) => (existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null);
const pct = (v) => `${Math.round(v * 100)}%`;
const signed = (v) => (v > 0 ? `+${v}` : `${v}`);

function pearson(points) {
  const n = points.length;
  if (n < 3) return NaN;
  let sx = 0, sy = 0, sxy = 0, sxx = 0, syy = 0;
  for (const [x, y] of points) { sx += x; sy += y; sxy += x * y; sxx += x * x; syy += y * y; }
  const d = Math.sqrt((n * sxx - sx * sx) * (n * syy - sy * sy));
  return d === 0 ? NaN : (n * sxy - sx * sy) / d;
}

const balance = read(P.balance);
const diversity = read(P.diversity);
if (!balance) {
  console.error('No artifacts/balance.json. Run:\n  npm run sim:balance -- --json artifacts/balance.json');
  process.exit(2);
}

if (process.argv.includes('--rebaseline')) {
  mkdirSync(dirname(P.baseline), { recursive: true });
  writeFileSync(P.baseline, `${JSON.stringify({
    recordedAt: new Date().toISOString(),
    simVersion: balance.simVersion,
    seedsPerPair: balance.seedsPerPair,
    note: 'Deliberate reference point. Re-record only as part of a balance pass, never to make a swing go away.',
    standings: balance.standings,
    perkCases: diversity?.cases ?? [],
  }, null, 2)}\n`);
  console.log(`rebaselined ${P.baseline}`);
  process.exit(0);
}

const baseline = read(P.baseline);
const baseBy = new Map((baseline?.standings ?? []).map((s) => [s.id, s]));
const rows = balance.standings.map((s) => {
  const was = baseBy.get(s.id);
  const now = Math.round(s.winRate * 100);
  const then = was ? Math.round(was.winRate * 100) : null;
  return { ...s, now, then, delta: then === null ? null : now - then };
});
const swings = rows.filter((r) => r.delta !== null && Math.abs(r.delta) >= SWING);

const r = pearson(balance.standings.map((s) => [s.budget, s.winRate]));
const baseR = baseline ? pearson(baseline.standings.map((s) => [s.budget, s.winRate])) : NaN;
const band = balance.summary?.outOfBandMatchups ?? 0;
const total = balance.summary?.totalMatchups ?? balance.matchups.length;

const L = [];
L.push('# Balance report');
L.push('');
L.push('_Generated by `npm run balance:report`. Nothing here fails a build —');
L.push('balance is its own pass. This exists so a swing cannot happen quietly._');
L.push('');
L.push(`- generated: ${balance.generatedAt}`);
L.push(`- sim ${balance.simVersion}, content \`${balance.contentHash}\`, ${balance.seedsPerPair} seeds/pair, ${balance.battles ?? '?'} battles`);
L.push(baseline
  ? `- baseline: ${baseline.recordedAt} (sim ${baseline.simVersion}, ${baseline.seedsPerPair ?? '?'} seeds/pair)`
  : '- baseline: **none recorded** — run `npm run balance:report -- --rebaseline`');
// Win rates are noisy at low seed counts, so a 10-seed run against a 20-seed
// baseline manufactures swings that are pure sampling. Say so rather than
// letting someone read seed noise as a regression.
const seedMismatch = baseline && baseline.seedsPerPair !== undefined
  && baseline.seedsPerPair !== balance.seedsPerPair;
if (seedMismatch) {
  L.push('');
  L.push(`> **Seed counts differ** — this run used ${balance.seedsPerPair}/pair, the baseline ${baseline.seedsPerPair}.`);
  L.push('> Deltas below include sampling noise. Re-run `npm run balance:collect` at the baseline\'s seed count before trusting them.');
}
L.push('');

L.push('## Headline');
L.push('');
L.push('| metric | now | baseline |');
L.push('|---|---|---|');
L.push(`| budget vs win-rate correlation | ${Number.isNaN(r) ? 'n/a' : r.toFixed(3)} | ${Number.isNaN(baseR) ? '—' : baseR.toFixed(3)} |`);
L.push(`| matchups outside the 35–65% band | ${band} / ${total} | — |`);
L.push(`| templates over the 70% kill criterion | ${balance.flagged.length}${balance.flagged.length ? ` (${balance.flagged.join(', ')})` : ''} | — |`);
L.push('');
L.push('A negative correlation means **spending more budget buys a worse mech**,');
L.push('which inverts the ladder: it generates opponents as `budget = f(node)`, so');
L.push('a run gets easier as it goes.');
L.push('');

L.push(`## Swings since baseline (±${SWING} points or more)`);
L.push('');
if (!baseline) L.push('_No baseline recorded, so nothing to compare._');
else if (swings.length === 0) L.push('None. Every build is within noise of the reference.');
else {
  L.push('| build | baseline | now | delta |');
  L.push('|---|---|---|---|');
  for (const s of swings.sort((a, b) => a.delta - b.delta)) {
    L.push(`| ${s.id} | ${s.then}% | ${s.now}% | **${signed(s.delta)}** |`);
  }
}
L.push('');

L.push('## Standings');
L.push('');
L.push('| build | budget | win rate | vs baseline |');
L.push('|---|---|---|---|');
for (const s of rows) {
  L.push(`| ${s.id} | ${s.budget} | ${s.now}% | ${s.delta === null ? '—' : signed(s.delta)} |`);
}
L.push('');

if (diversity) {
  L.push('## Perks');
  L.push('');
  L.push('Activation is read from `ModifierDef.isActive`, never restated here —');
  L.push('a retyped threshold once reported a live perk as dead.');
  L.push('');
  L.push('| perk | control | with perk | delta | active |');
  L.push('|---|---|---|---|---|');
  for (const c of diversity.cases ?? []) {
    L.push(`| ${c.id} | ${pct(c.controlWinRate)} | ${pct(c.perkWinRate)} | ${signed(Math.round(c.delta * 100))} pts | ${pct(c.activationRate)} |`);
  }
  L.push('');
  L.push(`Dead perks: ${diversity.deadPerks?.length ? diversity.deadPerks.join(', ') : 'none'}.`);
  L.push(`Dominant combinations: ${diversity.dominantCombinations?.length ? diversity.dominantCombinations.join(', ') : 'none'}.`);
  L.push('');
}

L.push('## Out-of-band matchups');
L.push('');
const out = balance.matchups.filter((m) => {
  const t = m.aWins + m.bWins + m.draws;
  const rate = t > 0 ? m.aWins / t : 0.5;
  return rate < 0.35 || rate > 0.65;
});
if (out.length === 0) L.push('None.');
else {
  L.push('| matchup | result | avg length |');
  L.push('|---|---|---|');
  for (const m of out) {
    L.push(`| ${m.a} vs ${m.b} | ${m.aWins}–${m.bWins}${m.draws ? `–${m.draws}` : ''} | ${m.avgDurationS.toFixed(1)}s |`);
  }
}
L.push('');
L.push('---');
L.push('');
L.push('Known causes and open questions: [docs/17-balance-findings.md](../docs/17-balance-findings.md).');
L.push('');

mkdirSync(dirname(P.out), { recursive: true });
writeFileSync(P.out, `${L.join('\n')}`);
console.log(`wrote ${P.out}`);
if (swings.length > 0) console.log(`${swings.length} swing(s) of ${SWING}+ points since baseline`);
