/**
 * The run's enemy ladder (docs/10 M4, docs/04 §5): budget-driven opponents
 * generated by the sim's pure `generateOpponent`, seeded per node so scouting
 * is honest — the card, the arena and the fight all derive from the same
 * seeds. Node flavors: standard / elite (+budget, +purse) / scrapyard (no
 * fight — buy used parts at poor rates, one reroll). All numbers are dials;
 * tuning deferred (Track C).
 */
import { generateOpponent, getChassis, getPart, headlineWeapon, Pcg32 } from '@mechbattler/sim';
import { RUN_LENGTH, SCRAP_BUY_MULT } from '../state/runState.js';
import type { OpponentDef } from './opponents.js';

// --- Ladder dials -----------------------------------------------------------
/** Tier budget = BASE + PER_NODE × node: 8 at node 1 → 30 at node 12 (04 §5). */
export const LADDER_BUDGET_BASE = 6;
export const LADDER_BUDGET_PER_NODE = 2;
export const ELITE_CHANCE = 0.25;
export const ELITE_BUDGET_BONUS = 4;
export const ELITE_PURSE_MULT = 1.5;
/** Scrapyard nodes per run (placed seeded, never node 1 or the last node). */
export const SCRAPYARD_COUNT = 2;
export const YARD_OFFER_COUNT = 4;
export const YARD_INTEGRITY_MIN = 0.55;
export const YARD_INTEGRITY_MAX = 0.95;

const EPITHETS = ['Rusty', 'Feral', 'Grim', 'Vagrant', 'Ashen', 'Copper', 'Howling', 'Pale'];
const SPAWN_DISTANCES_M = [60, 100, 160];

export function nodeBudget(nodeIndex: number): number {
  return LADDER_BUDGET_BASE + LADDER_BUDGET_PER_NODE * nodeIndex;
}

export type NodeKind = 'fight' | 'scrapyard';

/** Which nodes are scrapyards, fixed per run seed (never node 1 or the last). */
export function nodeKind(runSeed: number, nodeIndex: number): NodeKind {
  const rng = new Pcg32(runSeed ^ 0x9e3779b9);
  const yards = new Set<number>();
  while (yards.size < SCRAPYARD_COUNT) {
    yards.add(2 + Math.floor(rng.nextFloat() * (RUN_LENGTH - 2))); // 2..RUN_LENGTH-1
  }
  return yards.has(nodeIndex) ? 'scrapyard' : 'fight';
}

/** 2–3 scouted opponents for a fight node, generated from the node budget. */
export function ladderOpponents(runSeed: number, nodeIndex: number): OpponentDef[] {
  const countRng = new Pcg32(runSeed * 31 + nodeIndex);
  const count = 2 + (countRng.nextFloat() < 0.5 ? 1 : 0);
  return Array.from({ length: count }, (_, i) => {
    const cardSeed = (runSeed * 31 + nodeIndex) * 7 + i + 1;
    const rng = new Pcg32(cardSeed ^ 0x51ab);
    const elite = rng.nextFloat() < ELITE_CHANCE;
    const budget = nodeBudget(nodeIndex) + (elite ? ELITE_BUDGET_BONUS : 0);
    const gen = generateOpponent({ budget, seed: cardSeed });

    // Intel: two confirmed real parts (docs/04 §5), formatted like "W-AC Judge".
    const real = gen.build.parts.filter((p) => {
      const def = getPart(p.partId);
      return !def.isConduit && !def.isHeatPipe;
    });
    const confirmed: string[] = [];
    const seen = new Set<string>();
    for (let tries = 0; tries < 12 && confirmed.length < 2; tries++) {
      const def = getPart(real[Math.floor(rng.nextFloat() * real.length)]!.partId);
      if (seen.has(def.id)) continue;
      seen.add(def.id);
      confirmed.push(`${def.id} ${def.name.split(' ')[0]}`);
    }

    const chassis = getChassis(gen.build.chassisId);
    const epithet = EPITHETS[Math.floor(rng.nextFloat() * EPITHETS.length)]!;
    const spawnDistanceM = SPAWN_DISTANCES_M[Math.floor(rng.nextFloat() * SPAWN_DISTANCES_M.length)]!;
    const fillFrac = gen.spentTier / Math.max(budget, 1);
    return {
      id: `node-${nodeIndex}-${i}`,
      name: `${elite ? 'Elite ' : ''}${epithet} ${gen.templateName}`,
      blurb: gen.blurb,
      threat: (elite ? 3 : fillFrac > 0.85 ? 2 : 1) as 1 | 2 | 3,
      confirmed,
      build: gen.build,
      elite,
      battleSeed: cardSeed ^ 0x7ea51e,
      spawnDistanceM,
      chassisLabel: `${chassis.name} · ${chassis.type}`,
      headline: headlineWeapon(gen.build)?.name ?? null,
    };
  });
}

// --- Scrapyard --------------------------------------------------------------

export interface YardOffer {
  partId: string;
  integrity: number;
  price: number;
}

/** Parts a scrapyard node has on offer (used goods at palette prices). */
export function scrapyardOffers(runSeed: number, nodeIndex: number, rerolled: boolean): YardOffer[] {
  const rng = new Pcg32((runSeed * 131 + nodeIndex) ^ (rerolled ? 0x5eed : 0));
  // Everything real in the catalog, tier-capped by the node budget's half.
  const pool = ['W-MG', 'W-AC', 'W-LAS', 'W-CB', 'W-RKT', 'U-RAD', 'U-TC1', 'U-ARM', 'U-HS', 'P-CAP', 'R-C40', 'R-E25']
    .filter((id) => getPart(id).tier <= Math.max(2, Math.floor(nodeBudget(nodeIndex) / 2)));
  return Array.from({ length: YARD_OFFER_COUNT }, () => {
    const partId = pool[Math.floor(rng.nextFloat() * pool.length)]!;
    const def = getPart(partId);
    const integrity = YARD_INTEGRITY_MIN + rng.nextFloat() * (YARD_INTEGRITY_MAX - YARD_INTEGRITY_MIN);
    return {
      partId,
      integrity,
      price: Math.max(1, Math.ceil(def.tier * SCRAP_BUY_MULT * integrity)),
    };
  });
}
